# Server configuration
server:
  port: 8080
  max-http-header-size: 64KB
  tomcat:
    max-http-form-post-size: 320MB
    max-swallow-size: 320MB
  workerId: 0
  dataCenterId: 0

# Spring configuration
spring:
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 320MB
  redis:
    host: localhost
    port: 6379
    database: 0
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  data.mongodb:
    host: localhost
    port: 27017
    database: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3317/works?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=Asia/Shanghai
#   driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ABC#abc_123
    hikari:
      maximum-pool-size: 5
      auto-commit: true
      minimum-idle: 3

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

# JWT
jwt:
  header: Authorization
  secret: ow9ycVTT
  expiration: 3600
  tokenHead: Bearer
  route:
    authentication:
      login: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  file:
    path: /opt/logs

# Swagger Config
springfox:
  documentation:
    swagger-ui:
      enabled: true