# Server configuration
server:
  port: 8080
  workerId: 0
  dataCenterId: 0
  error:
    include-stacktrace: never
#  contextPath:

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data.mongodb:
    host: localhost
    port: 27017
    database: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3317/world?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ABC#abc_123
    hikari:
      maximum-pool-size: 5
      auto-commit: true
      minimum-idle: 3

# JWT
jwt:
  header: Authorization
  secret: ow9ycVTT
  expiration: 3600
  tokenHead: "Bearer "
  route:
    authentication:
      login: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
#logging:
#  level:
#    root: WARN
#    tech.tystnad.joblog: DEBUG
#    com.zaxxer.hikari.pool: DEBUG
#    org:
#      springframework: INFO
#      mybatis: INFO

# Swagger Config (true,false)
swagger:
  enable: true
#spring.boot.admin.url: http://localhost:8080
