package tech.tystnad.works.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import tech.tystnad.works.repository.domain.SysAuthorityDO;
import tech.tystnad.works.repository.domain.SysAuthorityDOExample;

public interface SysAuthorityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    long countByExample(SysAuthorityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int deleteByExample(SysAuthorityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int insert(SysAuthorityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int insertSelective(SysAuthorityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    List<SysAuthorityDO> selectByExampleWithRowbounds(SysAuthorityDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    List<SysAuthorityDO> selectByExample(SysAuthorityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    SysAuthorityDO selectByPrimaryKey(Integer authId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysAuthorityDO record, @Param("example") SysAuthorityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysAuthorityDO record, @Param("example") SysAuthorityDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAuthorityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAuthorityDO record);
}