package tech.tystnad.works.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import tech.tystnad.works.repository.domain.SysOrgUserDO;
import tech.tystnad.works.repository.domain.SysOrgUserDOExample;

public interface SysOrgUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    long countByExample(SysOrgUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int deleteByExample(SysOrgUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int insert(SysOrgUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int insertSelective(SysOrgUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    List<SysOrgUserDO> selectByExampleWithRowbounds(SysOrgUserDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    List<SysOrgUserDO> selectByExample(SysOrgUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    SysOrgUserDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysOrgUserDO record, @Param("example") SysOrgUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysOrgUserDO record, @Param("example") SysOrgUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOrgUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOrgUserDO record);
}