package tech.tystnad.works.repository.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import tech.tystnad.works.repository.domain.SysOrganizationDO;
import tech.tystnad.works.repository.domain.SysOrganizationDOExample;

import java.util.List;

public interface SysOrganizationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    long countByExample(SysOrganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int deleteByExample(SysOrganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int insert(SysOrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int insertSelective(SysOrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    List<SysOrganizationDO> selectByExampleWithRowbounds(SysOrganizationDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    List<SysOrganizationDO> selectByExample(SysOrganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    SysOrganizationDO selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysOrganizationDO record, @Param("example") SysOrganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysOrganizationDO record, @Param("example") SysOrganizationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOrganizationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOrganizationDO record);
}