package tech.tystnad.works.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import tech.tystnad.works.repository.domain.WorkNextPlanDO;
import tech.tystnad.works.repository.domain.WorkNextPlanDOExample;

public interface WorkNextPlanDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    long countByExample(WorkNextPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int deleteByExample(WorkNextPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int insert(WorkNextPlanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int insertSelective(WorkNextPlanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    List<WorkNextPlanDO> selectByExampleWithRowbounds(WorkNextPlanDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    List<WorkNextPlanDO> selectByExample(WorkNextPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    WorkNextPlanDO selectByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WorkNextPlanDO record, @Param("example") WorkNextPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WorkNextPlanDO record, @Param("example") WorkNextPlanDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkNextPlanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_next_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkNextPlanDO record);
}