package tech.tystnad.works.repository.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import tech.tystnad.works.repository.domain.WorkPlanTextDO;
import tech.tystnad.works.repository.domain.WorkPlanTextDOExample;

public interface WorkPlanTextDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    long countByExample(WorkPlanTextDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int deleteByExample(WorkPlanTextDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long planTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int insert(WorkPlanTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int insertSelective(WorkPlanTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    List<WorkPlanTextDO> selectByExampleWithRowbounds(WorkPlanTextDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    List<WorkPlanTextDO> selectByExample(WorkPlanTextDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    WorkPlanTextDO selectByPrimaryKey(Long planTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WorkPlanTextDO record, @Param("example") WorkPlanTextDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WorkPlanTextDO record, @Param("example") WorkPlanTextDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkPlanTextDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan_text
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkPlanTextDO record);
}