package tech.tystnad.works.repository.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_log
 */
public class SysLogDO {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_id
     *
     * @mbg.generated
     */
    private Integer logId;

    /**
     * Database Column Remarks:
     *   操作者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.operator
     *
     * @mbg.generated
     */
    private Long operator;

    /**
     * Database Column Remarks:
     *   操作模块
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.module
     *
     * @mbg.generated
     */
    private String module;

    /**
     * Database Column Remarks:
     *   操作功能
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.features
     *
     * @mbg.generated
     */
    private Integer features;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_id
     *
     * @return the value of sys_log.log_id
     *
     * @mbg.generated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_id
     *
     * @param logId the value for sys_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.operator
     *
     * @return the value of sys_log.operator
     *
     * @mbg.generated
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.operator
     *
     * @param operator the value for sys_log.operator
     *
     * @mbg.generated
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.module
     *
     * @return the value of sys_log.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.module
     *
     * @param module the value for sys_log.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.features
     *
     * @return the value of sys_log.features
     *
     * @mbg.generated
     */
    public Integer getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.features
     *
     * @param features the value for sys_log.features
     *
     * @mbg.generated
     */
    public void setFeatures(Integer features) {
        this.features = features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}