package tech.tystnad.works.repository.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_organization
 */
public class SysOrganizationDO {
    /**
     * Database Column Remarks:
     *   机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     *   顶级机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.top_id
     *
     * @mbg.generated
     */
    private Long topId;

    /**
     * Database Column Remarks:
     *   父级机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   层级(从0开始,最大5级)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.org_level
     *
     * @mbg.generated
     */
    private Byte orgLevel;

    /**
     * Database Column Remarks:
     *   机构名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     * Database Column Remarks:
     *   状态(1-启用,0-禁用)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     * Database Column Remarks:
     *   是否删除(1-删除,0-未删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.updater
     *
     * @mbg.generated
     */
    private Long updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.creator
     *
     * @mbg.generated
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_organization.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.org_id
     *
     * @return the value of sys_organization.org_id
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.org_id
     *
     * @param orgId the value for sys_organization.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.top_id
     *
     * @return the value of sys_organization.top_id
     *
     * @mbg.generated
     */
    public Long getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.top_id
     *
     * @param topId the value for sys_organization.top_id
     *
     * @mbg.generated
     */
    public void setTopId(Long topId) {
        this.topId = topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.parent_id
     *
     * @return the value of sys_organization.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.parent_id
     *
     * @param parentId the value for sys_organization.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.org_level
     *
     * @return the value of sys_organization.org_level
     *
     * @mbg.generated
     */
    public Byte getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.org_level
     *
     * @param orgLevel the value for sys_organization.org_level
     *
     * @mbg.generated
     */
    public void setOrgLevel(Byte orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.org_name
     *
     * @return the value of sys_organization.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.org_name
     *
     * @param orgName the value for sys_organization.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.enabled
     *
     * @return the value of sys_organization.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.enabled
     *
     * @param enabled the value for sys_organization.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.deleted
     *
     * @return the value of sys_organization.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.deleted
     *
     * @param deleted the value for sys_organization.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.updater
     *
     * @return the value of sys_organization.updater
     *
     * @mbg.generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.updater
     *
     * @param updater the value for sys_organization.updater
     *
     * @mbg.generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.creator
     *
     * @return the value of sys_organization.creator
     *
     * @mbg.generated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.creator
     *
     * @param creator the value for sys_organization.creator
     *
     * @mbg.generated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.update_time
     *
     * @return the value of sys_organization.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.update_time
     *
     * @param updateTime the value for sys_organization.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_organization.create_time
     *
     * @return the value of sys_organization.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_organization.create_time
     *
     * @param createTime the value for sys_organization.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}