package tech.tystnad.works.repository.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table work_plan_text
 */
public class WorkPlanTextDO {
    /**
     * Database Column Remarks:
     *   计划内容ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.plan_text_id
     *
     * @mbg.generated
     */
    private Long planTextId;

    /**
     * Database Column Remarks:
     *   机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     *   顶级机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.top_id
     *
     * @mbg.generated
     */
    private Long topId;

    /**
     * Database Column Remarks:
     *   明天计划
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.plan
     *
     * @mbg.generated
     */
    private String plan;

    /**
     * Database Column Remarks:
     *   激活次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.total
     *
     * @mbg.generated
     */
    private Short total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.updater
     *
     * @mbg.generated
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.creator
     *
     * @mbg.generated
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_plan_text.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.plan_text_id
     *
     * @return the value of work_plan_text.plan_text_id
     *
     * @mbg.generated
     */
    public Long getPlanTextId() {
        return planTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.plan_text_id
     *
     * @param planTextId the value for work_plan_text.plan_text_id
     *
     * @mbg.generated
     */
    public void setPlanTextId(Long planTextId) {
        this.planTextId = planTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.org_id
     *
     * @return the value of work_plan_text.org_id
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.org_id
     *
     * @param orgId the value for work_plan_text.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.top_id
     *
     * @return the value of work_plan_text.top_id
     *
     * @mbg.generated
     */
    public Long getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.top_id
     *
     * @param topId the value for work_plan_text.top_id
     *
     * @mbg.generated
     */
    public void setTopId(Long topId) {
        this.topId = topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.plan
     *
     * @return the value of work_plan_text.plan
     *
     * @mbg.generated
     */
    public String getPlan() {
        return plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.plan
     *
     * @param plan the value for work_plan_text.plan
     *
     * @mbg.generated
     */
    public void setPlan(String plan) {
        this.plan = plan == null ? null : plan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.total
     *
     * @return the value of work_plan_text.total
     *
     * @mbg.generated
     */
    public Short getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.total
     *
     * @param total the value for work_plan_text.total
     *
     * @mbg.generated
     */
    public void setTotal(Short total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.updater
     *
     * @return the value of work_plan_text.updater
     *
     * @mbg.generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.updater
     *
     * @param updater the value for work_plan_text.updater
     *
     * @mbg.generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.creator
     *
     * @return the value of work_plan_text.creator
     *
     * @mbg.generated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.creator
     *
     * @param creator the value for work_plan_text.creator
     *
     * @mbg.generated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.update_time
     *
     * @return the value of work_plan_text.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.update_time
     *
     * @param updateTime the value for work_plan_text.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_plan_text.create_time
     *
     * @return the value of work_plan_text.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_plan_text.create_time
     *
     * @param createTime the value for work_plan_text.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}