package tech.tystnad.works.repository.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table work_next_plan
 */
public class WorkNextPlanDO {
    /**
     * Database Column Remarks:
     *   计划ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.plan_id
     *
     * @mbg.generated
     */
    private Long planId;

    /**
     * Database Column Remarks:
     *   机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     *   顶级机构ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.top_id
     *
     * @mbg.generated
     */
    private Long topId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   计划内容ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.plan_text_id
     *
     * @mbg.generated
     */
    private Long planTextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.updater
     *
     * @mbg.generated
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   创建用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.creator
     *
     * @mbg.generated
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_next_plan.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.plan_id
     *
     * @return the value of work_next_plan.plan_id
     *
     * @mbg.generated
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.plan_id
     *
     * @param planId the value for work_next_plan.plan_id
     *
     * @mbg.generated
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.org_id
     *
     * @return the value of work_next_plan.org_id
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.org_id
     *
     * @param orgId the value for work_next_plan.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.top_id
     *
     * @return the value of work_next_plan.top_id
     *
     * @mbg.generated
     */
    public Long getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.top_id
     *
     * @param topId the value for work_next_plan.top_id
     *
     * @mbg.generated
     */
    public void setTopId(Long topId) {
        this.topId = topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.user_id
     *
     * @return the value of work_next_plan.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.user_id
     *
     * @param userId the value for work_next_plan.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.plan_text_id
     *
     * @return the value of work_next_plan.plan_text_id
     *
     * @mbg.generated
     */
    public Long getPlanTextId() {
        return planTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.plan_text_id
     *
     * @param planTextId the value for work_next_plan.plan_text_id
     *
     * @mbg.generated
     */
    public void setPlanTextId(Long planTextId) {
        this.planTextId = planTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.updater
     *
     * @return the value of work_next_plan.updater
     *
     * @mbg.generated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.updater
     *
     * @param updater the value for work_next_plan.updater
     *
     * @mbg.generated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.creator
     *
     * @return the value of work_next_plan.creator
     *
     * @mbg.generated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.creator
     *
     * @param creator the value for work_next_plan.creator
     *
     * @mbg.generated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.update_time
     *
     * @return the value of work_next_plan.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.update_time
     *
     * @param updateTime the value for work_next_plan.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_next_plan.create_time
     *
     * @return the value of work_next_plan.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_next_plan.create_time
     *
     * @param createTime the value for work_next_plan.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}