package tech.tystnad.works.model.dto;

import java.util.Date;

public class SysUserDTO {
    /**
     * Database Column Remarks:
     * 机构ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_id
     */
    private Long orgId;

    /**
     * Database Column Remarks:
     * 顶级机构ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.top_id
     */
    private Long topId;

    /**
     * Database Column Remarks:
     * 用户名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     */
    private String userName;

    /**
     * Database Column Remarks:
     * 密码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_cipher
     */
    private String userCipher;

    /**
     * Database Column Remarks:
     * 角色ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.role_id
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     * 昵称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nickname
     */
    private String nickname;

    /**
     * Database Column Remarks:
     * 邮箱
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.updater
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.creator
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_id
     *
     * @return the value of sys_user.org_id
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_id
     *
     * @param orgId the value for sys_user.org_id
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.top_id
     *
     * @return the value of sys_user.top_id
     */
    public Long getTopId() {
        return topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.top_id
     *
     * @param topId the value for sys_user.top_id
     */
    public void setTopId(Long topId) {
        this.topId = topId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_cipher
     *
     * @return the value of sys_user.user_cipher
     */
    public String getUserCipher() {
        return userCipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_cipher
     *
     * @param userCipher the value for sys_user.user_cipher
     */
    public void setUserCipher(String userCipher) {
        this.userCipher = userCipher == null ? null : userCipher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role_id
     *
     * @return the value of sys_user.role_id
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role_id
     *
     * @param roleId the value for sys_user.role_id
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nickname
     *
     * @return the value of sys_user.nickname
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nickname
     *
     * @param nickname the value for sys_user.nickname
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.updater
     *
     * @return the value of sys_user.updater
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.updater
     *
     * @param updater the value for sys_user.updater
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.creator
     *
     * @return the value of sys_user.creator
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.creator
     *
     * @param creator the value for sys_user.creator
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
